export const identityServerUrl = "https://meidox-identityserver.solocode.click";
export const meidoxApiUrl = "https://meidoxapi.solocode.click";

const apiLinks = {
  workShift: {
    getWorkShift: `${meidoxApiUrl}/WorkShift`,
  },
  machines: {
    getMachines: `${meidoxApiUrl}/Machine`,
  },
  worksession: {
    create: `${meidoxApiUrl}/WorkSession`,
    getById: `${meidoxApiUrl}/WorkSession`,
    createWorkSessionSetup: `${meidoxApiUrl}/WorkSessionSetup`,
    getWorkSessionSetupById: `${meidoxApiUrl}/WorkSessionSetup`,
    updateAdjustmentItemUnit: `${meidoxApiUrl}/WorkSessionSetup/AdjustmentItemUnit`,
    updateAdjustmentItemKg: `${meidoxApiUrl}/WorkSessionSetup/AdjustmentItemKg`,
    updateRemark: `${meidoxApiUrl}/WorkSessionSetup/Remark`,
    completeWorkSessionSetup: `${meidoxApiUrl}/WorkSessionSetup/Complete`,
    pauseWorkSessionSetup: `${meidoxApiUrl}/WorkSessionSetup/Pause`,
    workSessionSetupByWsId: `${meidoxApiUrl}/WorkSessionSetup/WorkSession`,
  },
  workSessionProduction: {
    create: `${meidoxApiUrl}/WorkSessionProduction`,
    getWorkSessionProductionById: `${meidoxApiUrl}/WorkSessionProduction`,
    updateNumberOfGoodProduct: `${meidoxApiUrl}/WorkSessionProduction/NumberOfGoodProduct`,
    updateCanNumber: `${meidoxApiUrl}/WorkSessionProduction/CanNumber`,
    updateRemark: `${meidoxApiUrl}/WorkSessionProduction/Remark`,
    completeWorkSessionProduction: `${meidoxApiUrl}/WorkSessionProduction/Complete`,
    pauseWorkSessionProduction: `${meidoxApiUrl}/WorkSessionProduction/Pause`,
    getWorkSessionProductionByWsId: `${meidoxApiUrl}/WorkSessionProduction/WorkSession`,
  },
  workSessionMoldChange: {
    create: `${meidoxApiUrl}/WorkSessionMoldChange`,
    getWorkSessionMoldChangeById: `${meidoxApiUrl}/WorkSessionMoldChange`,
    updateWorkSessionMoldChange: `${meidoxApiUrl}/WorkSessionMoldChange/Remark`,
    completeWorkSessionMoldChange: `${meidoxApiUrl}/WorkSessionMoldChange/Complete`,
    getWorkSessionMoldChangeByWsId: `${meidoxApiUrl}/WorkSessionMoldChange/WorkSession`,
  },
  workSessionMaterialChange: {
    create: `${meidoxApiUrl}/WorkSessionMaterialChange`,
    getWorkSessionMatertialChangeById: `${meidoxApiUrl}/WorkSessionMaterialChange`,
    updateWorkSessionMatertialChangeRemark: `${meidoxApiUrl}/WorkSessionMaterialChange/Remark`,
    completeWorkSessionMatertialChange: `${meidoxApiUrl}/WorkSessionMaterialChange/Complete`,
    getWorkSessionMatertialChangeByWsId: `${meidoxApiUrl}/WorkSessionMaterialChange/WorkSession`,
  },
  workSessionAdjustmentBegin: {
    create: `${meidoxApiUrl}/WorkSessionAdjustmentBegin`,
    getWorkSessionAdjustmentBeginById: `${meidoxApiUrl}/WorkSessionAdjustmentBegin`,
    updateWorkSessionAdjustmentBeginRemark: `${meidoxApiUrl}/WorkSessionAdjustmentBegin/Remark`,
    completeWorkSessionAdjustmentBegin: `${meidoxApiUrl}/WorkSessionAdjustmentBegin/Complete`,
    getWorkSessionAdjustmentBeginByWsId: `${meidoxApiUrl}/WorkSessionAdjustmentBegin/WorkSession`,
  },
  workSession4S: {
    create: `${meidoxApiUrl}/WorkSession4S`,
    getWorkSession4SById: `${meidoxApiUrl}/WorkSession4S`,
    updateWorkSession4SRemark: `${meidoxApiUrl}/WorkSession4S/Remark`,
    completeWorkSession4S: `${meidoxApiUrl}/WorkSession4S/Complete`,
    getWorkSession4SByWsId: `${meidoxApiUrl}/WorkSession4S/WorkSession`,
  },
  workSessionProductionPrepCheck: {
    create: `${meidoxApiUrl}/WorkSessionProductionPrepCheck`,
    getWorkSessionProductionPrepCheckById: `${meidoxApiUrl}/WorkSessionProductionPrepCheck`,
    updateWorkSessionProductionPrepCheckRemark: `${meidoxApiUrl}/WorkSessionProductionPrepCheck/Remark`,
    completeWorkSessionProductionPrepCheck: `${meidoxApiUrl}/WorkSessionProductionPrepCheck/Complete`,
    getWorkSessionProductionPrepCheckByWsId: `${meidoxApiUrl}/WorkSessionProductionPrepCheck/WorkSession`,
  },
  workSessionSorting: {
    create: `${meidoxApiUrl}/WorkSessionSorting`,
    getWorkSessionSortingById: `${meidoxApiUrl}/WorkSessionSorting`,
    updateWorkSessionSortingRemark: `${meidoxApiUrl}/WorkSessionSorting/Remark`,
    completeWorkSessionSorting: `${meidoxApiUrl}/WorkSessionSorting/Complete`,
    getWorkSessionSortingByWsId: `${meidoxApiUrl}/WorkSessionSorting/WorkSession`,
  },
  workSessionOtherStop: {
    create: `${meidoxApiUrl}/WorkSessionOtherStop`,
    getWorkSessionOtherStopById: `${meidoxApiUrl}/WorkSessionOtherStop`,
    updateWorkSessionOtherStopRemark: `${meidoxApiUrl}/WorkSessionOtherStop/Remark`,
    completeWorkSessionOtherStop: `${meidoxApiUrl}/WorkSessionOtherStop/Complete`,
    getWorkSessionOtherStopByWsId: `${meidoxApiUrl}/WorkSessionOtherStop/WorkSession`,
  },
  workSessionEquipmentRepair: {
    create: `${meidoxApiUrl}/WorkSessionEquipmentRepair`,
    getWorkSessionEquipmentRepairById: `${meidoxApiUrl}/WorkSessionEquipmentRepair`,
    updateWorkSessionEquipmentRepairRemark: `${meidoxApiUrl}/WorkSessionEquipmentRepair/Remark`,
    completeWorkSessionEquipmentRepair: `${meidoxApiUrl}/WorkSessionEquipmentRepair/Complete`,
    getWorkSessionEquipmentRepairByWsId: `${meidoxApiUrl}/WorkSessionEquipmentRepair/WorkSession`,
  },
  workSessionOtherMachineSupport: {
    create: `${meidoxApiUrl}/WorkSessionOtherMachineSupport`,
    getWorkSessionOtherMachineSupportById: `${meidoxApiUrl}/WorkSessionOtherMachineSupport`,
    updateWorkSessionOtherMachineSupportRemark: `${meidoxApiUrl}/WorkSessionOtherMachineSupport/Remark`,
    completeWorkSessionOtherMachineSupport: `${meidoxApiUrl}/WorkSessionOtherMachineSupport/Complete`,
    getWorkSessionOtherMachineSupportByWsId: `${meidoxApiUrl}/WorkSessionOtherMachineSupport/WorkSession`,
  },
  workSessionQualityCheck: {
    create: `${meidoxApiUrl}/WorkSessionQualityCheck`,
    getWorkSessionQualityCheckById: `${meidoxApiUrl}/WorkSessionQualityCheck`,
    updateWorkSessionQualityCheckRemark: `${meidoxApiUrl}/WorkSessionQualityCheck/Remark`,
    completeWorkSessionQualityCheck: `${meidoxApiUrl}/WorkSessionQualityCheck/Complete`,
    getWorkSessionQualityCheckByWsId: `${meidoxApiUrl}/WorkSessionQualityCheck/WorkSession`,
  },
  reasonForStoppingBreakStart: {
    create: `${meidoxApiUrl}/ReasonForStoppingBreakStart`,
    getReasonForStoppingBreakStartById: `${meidoxApiUrl}/ReasonForStoppingBreakStart`,
    updateReasonForStoppingBreakStartRemark: `${meidoxApiUrl}/ReasonForStoppingBreakStart/Remark`,
    completeReasonForStoppingBreakStart: `${meidoxApiUrl}/ReasonForStoppingBreakStart/Complete`,
    getReasonForStoppingBreakStartByWsId: `${meidoxApiUrl}/ReasonForStoppingBreakStart/WorkSession`,
  },
  reasonForStoppingNoKanbanStart: {
    create: `${meidoxApiUrl}/ReasonForStoppingNoKanbanStart`,
    getReasonForStoppingNoKanbanStartById: `${meidoxApiUrl}/ReasonForStoppingNoKanbanStart`,
    updateReasonForStoppingNoKanbanStartRemark: `${meidoxApiUrl}/ReasonForStoppingNoKanbanStart/Remark`,
    completeReasonForStoppingNoKanbanStart: `${meidoxApiUrl}/ReasonForStoppingNoKanbanStart/Complete`,
    getReasonForStoppingNoKanbanStartByWsId: `${meidoxApiUrl}/ReasonForStoppingNoKanbanStart/WorkSession`,
  },
  reasonForStoppingMeetingStart: {
    create: `${meidoxApiUrl}/ReasonForStoppingMeetingStart`,
    getReasonForStoppingMeetingStartById: `${meidoxApiUrl}/ReasonForStoppingMeetingStart`,
    updateReasonForStoppingMeetingStartRemark: `${meidoxApiUrl}/ReasonForStoppingMeetingStart/Remark`,
    completeReasonForStoppingMeetingStart: `${meidoxApiUrl}/ReasonForStoppingMeetingStart/Complete`,
    getReasonForStoppingMeetingStartByWsId: `${meidoxApiUrl}/ReasonForStoppingMeetingStart/WorkSession`,
  },
  reasonForStoppingMaterialMoldShortage: {
    create: `${meidoxApiUrl}/ReasonForStoppingMaterialMoldShortage`,
    getReasonForStoppingMaterialMoldShortageById: `${meidoxApiUrl}/ReasonForStoppingMaterialMoldShortage`,
    updateReasonForStoppingMaterialMoldShortageRemark: `${meidoxApiUrl}/ReasonForStoppingMaterialMoldShortage/Remark`,
    completeReasonForStoppingMaterialMoldShortage: `${meidoxApiUrl}/ReasonForStoppingMaterialMoldShortage/Complete`,
    getReasonForStoppingMaterialMoldShortageByWsId: `${meidoxApiUrl}/ReasonForStoppingMaterialMoldShortage/WorkSession`,
  },
  reasonForStoppingPlannedMaintenance: {
    create: `${meidoxApiUrl}/ReasonForStoppingPlannedMaintenance`,
    getReasonForStoppingPlannedMaintenanceById: `${meidoxApiUrl}/ReasonForStoppingPlannedMaintenance`,
    updateReasonForStoppingPlannedMaintenanceRemark: `${meidoxApiUrl}/ReasonForStoppingPlannedMaintenance/Remark`,
    completeReasonForStoppingPlannedMaintenance: `${meidoxApiUrl}/ReasonForStoppingPlannedMaintenance/Complete`,
    getReasonForStoppingPlannedMaintenanceByWsId: `${meidoxApiUrl}/ReasonForStoppingPlannedMaintenance/WorkSession`,
  },
  reasonForStoppingNoOperator: {
    create: `${meidoxApiUrl}/ReasonForStoppingNoOperator`,
    getReasonForStoppingNoOperatorById: `${meidoxApiUrl}/ReasonForStoppingNoOperator`,
    updateReasonForStoppingNoOperatorRemark: `${meidoxApiUrl}/ReasonForStoppingNoOperator/Remark`,
    completeReasonForStoppingNoOperator: `${meidoxApiUrl}/ReasonForStoppingNoOperator/Complete`,
    getReasonForStoppingNoOperatorByWsId: `${meidoxApiUrl}/ReasonForStoppingNoOperator/WorkSession`,
  },
  reasonForStoppingFourSAfterLunchStart: {
    create: `${meidoxApiUrl}/ReasonForStoppingFourSAfterLunchStart`,
    getReasonForStoppingFourSAfterLunchStartById: `${meidoxApiUrl}/ReasonForStoppingFourSAfterLunchStart`,
    updateReasonForStoppingFourSAfterLunchStartRemark: `${meidoxApiUrl}/ReasonForStoppingFourSAfterLunchStart/Remark`,
    completeReasonForStoppingFourSAfterLunchStart: `${meidoxApiUrl}/ReasonForStoppingFourSAfterLunchStart/Complete`,
    getReasonForStoppingFourSAfterLunchStartByWsId: `${meidoxApiUrl}/ReasonForStoppingFourSAfterLunchStart/WorkSession`,
  },
};

export default apiLinks;
