name: CD - Deploy with Helm

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag to deploy"
        required: true
        default: "latest"

  workflow_run:
    workflows: ["CI - Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Decode and set KUBECONFIG
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
          echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      # The KUBECONFIG env var is automatically exported and picked up by kubectl.
      - id: "get-pods"
        run: "kubectl get pods"

      - name: Deploy with Helm
        run: |
          helm upgrade --install meidox-fe ./meidoxfe --namespace meidox --create-namespace \
            -f ./meidoxfe/values.yaml \
            --set image.repository=${{ secrets.SOLOCODE_USERNAME }}/meidox-fe \
            --set image.tag=${{ env.IMAGE_TAG  }}
